steps:
- name: 'heroku/buildpacks'
  volumes:
  - name: 'lifecycle'
    path: '/lifecycle'
  entrypoint: '/lifecycle/detector'
  args: ['-app', '/workspace']
- name: 'heroku/buildpacks'
  volumes:
  - name: 'layers'
    path: '/layers'
  entrypoint: '/lifecycle/builder'
  args: ['-app', '/workspace', '-layers', '/layers']
- name: 'gcr.io/cloud-builders/docker'
  volumes:
  - name: 'lifecycle'
    path: '/lifecycle'
  - name: 'layers'
    path: '/layers'
  entrypoint: '/lifecycle/exporter'
  args: ['-app', '/workspace', '-layers', '/layers', '-image', 'heroku/buildpacks', '-group', '/workspace/group.toml', '-daemon', 'gcr.io/$PROJECT_ID/$REPO_NAME']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
